### ISSUE TITLE
Unnecessary tracked directories?

### ISSUE THREAD

**Issue by NateDimick** [codeforUV/ruralnet#2]
Every time I use `git status` in my terminal, most of the changes are to the `__sapper__` and `src/node_modules` directories. Do these directories really need to be tracked, or are they automatically built/maintained by the Sapper framework/ NPM in each individual installation? 

Basically, could we add `__sapper__` and  `src/node_modules` (and possibly others) to .gitignore without causing issues? If so, I think it should be done to make this repository easier to work with and have a smaller total remote file size.

**Comment by ejolly** [comment]
Yup totally just did that. Thanks for the suggestion.
