### ISSUE TITLE
Style web app

### ISSUE THREAD

**Issue by ejolly** [codeforUV/ruralnet#8]
@jmslynn working on HTML + CSS template(s) and will hand off to @ejolly to incorporate into app.

**Comment by colbyhemond** [comment]
@jmslynn provided base template.

I have been able to incorporate into my local copy of the project. Will create draft PR soon.

**Comment by colbyhemond** [comment]
Initial styling has been added. There is some extra cleanup/changes that can be made. We can make additional issues for specifics when needed.
